=head1 NAME

perlfaq1 - Allgemeine Fragen zu Perl

=head1 Beschreibung

Dieser Abschnitt der FAQ beantwortet sehr allgemeine, high-level Fragen
über Perl.

=head2 Was ist Perl?

Perl ist eine Hochsprache der Programmierung mit einer aus verschiedenen Quellen 
schöpfenden Herkunft, die von Larry Wall und einem Ensemble von tausenden anderen 
geschrieben wurde.
Sie wurde der allgegenwärtigen C-Programmiersprache hergeleitet und
in einem geringeren Außmaß auch von sed, awk, der Unix shell und mindestens
einem Dutzend andere Tools und Sprachen. Perls Prozess-, Datei-, und 
Textmanipulationsfähigkeiten machen es besonders gut geeignet für Aufgaben mit 
schnellem Prototypen, Systemtools, Softwaretools, Systembetreuungsaufgaben, 
Datatenbankzugriff, graphischem Programmieren, Netzwerk, und World-Wide-Web-Programmierung. 
Diese Stärken haben es besonders bei Systembetreuern, CGI-Skript-Autoren beliebt gemacht, 
doch auch Mathematiker, Genforscher, Journalisten und sogar Manager verwenden Perl. 
Vielleicht solltest auch du es tun. 

=head2 Wer unterstützt Perl?  Wer entwickelt es?  Warum ist es kostenlos?

Die ursprüngliche Kultur des Internets, bevor es populär wurde, und die tiefe 
Gläubigkeit des Perl-Autors, Larry Wall, haben zur freien und offenen Verteilungsmethode 
von Perl geführt. Perl wird von seinen Anwendern unterstützt. Der Core (Kern), die 
Standard-Perl-Bibliothek, die optionalen Module und die Dokumentation, die Du gerade liest 
wurden alle von Freiwilligen geschrieben. Siehe die persönliche Mitteilung am Ende der Datei 
"README" in der Perl Source Distribution zu weiteren Einzelheiten. Siehe auch L<perlhist>
(neu ab 5.005) zu Perls Meilenstein-Versionen. 

Speziell das Entwickler-Team des Cores (auch bekannt als Perl Porters) ist eine buntgemischte
Gruppe von selbstlosen Individuen, die sich dafür einsetzen, eine bessere, kostenlose Software
zu schreiben, als Du es hoffen kannst, für Geld zu kaufen. Vielleicht möchtest Du die laufende
Entwicklung über die Archive unter http://www.xray.mpe.mpg.de/mailing-lists/perl5-porters/
und http://archive.develooper.com/perl5-porters@perl.org/ oder über das Newsgateway
nntp://nntp.perl.org/perl.perl5.porters oder dessen Webinterface unter http://nntp.perl.org/group/perl.perl5.porters 
verfolgen, oder die FAQ unter http://dev.perl.org/perl5/docs/p5p-faq.html lesen. Du kannst Dich
auch auf der Mailinliste einschreiben, indem Du eine Anfrage an perl5-porters-request@perl.org 
schickst (eine leere Nachricht ohne Betreff ist ausreichend).

Obwohl das GNU Projekt Perl beinhaltet, gibt es nicht so etwas wie "GNU Perl". Perl wird
von der Free Software Foundation weder geschrieben noch gepflegt. Perls Lizenzbedingungen
sind auch freier als es GNU Software normalerweise ist.

Auf Wunsch kannst Du kommerzielle Unterstützung für Perl bekommen, aber für die meisten
Anwender wird der informelle Support mehr als ausreichend sein. Für weitere Informationen
siehe auch die Antwort auf die Frage "Wo kann ich eine kommerzielle Version von Perl kaufen?".

=head2 Welche Version von Perl soll ich benutzen?

(beigetragen von brian d foy)

Oft ist es eine Sache der eigenen Meinung und des Geschmacks und es gibt keine
Anwort, die für jeden passt. Im Allgemeinen solltest Du entweder die akutelle
stabile Version verwenden oder die stabile Version, die es unmittelbar vor der
aktuellen Version gab. Aktuell sind dies perl5.10.x und perl5.8.x.

Weiterhin musst Du weitere Dinge beachten und entscheiden, was für Dich das
Beste ist.

=over 4

=item *

Wenn die Dinge nicht kaputt sind, kann ein Perl-Upgrade sie kaputt machen (oder zumindest
neue Warnungen erzeugen).

=item *

Die aktuellsten Versionen von perl haben mehr Bugfixes.

=item *

Die Perl Community ist darauf eingestellt, die letzten Versionen zu unterstützen,
also wirst Du es leichter haben, Hilfe für diese zu bekommen.

=item *

Versionen vor perl5.004 haben schwerwiegende Sicherheitsprobleme mit
"buffer overflows" und einige Fälle haben CERT Hinweise (z.B. 
http://www.cert.org/advisories/CA-1997-17.html ).

=item *

Die aktuellsten Versionen sind wahrscheinlich die am wenigsten eingesetzten
und getestetn, so dass Du vielleicht ein paar Monate nach ihrer Veröffentlichung
abwarten willst wenn Du Risikoscheu bist und sehen willst, welche Probleme andere haben.

=item *

Die unmittelbar vorhergehenden Versionen (z.B. perl5.8.x) sind für gewöhnlich seit
einer ganzen Weile gepflegt, auch wenn nicht auf dem gleichen Level wie die aktuelle
Version.

=item *

Niemand unterstützt aktiv Perl 4. Vor fünf Jahren war es ein toter Kamelkadaver
(diesem Dokument zufolge). Jetzt es kaum noch ein Skelett, weil seine getünchten
Knochen gebrochen und angefressen sind.

=item *

Es steht kein Perl 6 Release an, aber es wird da sein, wenn es fertig ist. Bleib dran,
aber kümmere Dich nicht darum, dass Du einen Versionsprung von Perl machen musst. Keiner
wird Dir Perl 5 wegnehmen.

=item *

Es gibt wirklich zwei Gleise bei der perl Entwicklung: Eine gepflegte Version und eine
experimentelle Version. Die gepflegte Version ist stabil und hat eine gerade  
Neben-Versionsnummer (z.B. perl5.10.x, bei der die 10 die Neben-Versionsnummer ist).
Die experimentelle Version kann Features enthalten, die es nicht bis in die stabile
Version schaffen. Sie haben eine ungerade Neben-Versionsnummer (z.B. perl5.9.x, wobei
die 9 die Neben-Versionsnummer ist).

=back


=head2 Was sind Perl 4, Perl 5 und Perl 6?

(beigetragen von brian d foy)

Kurz, Perl 4 ist die Vergangenheit, Perl 5 die Gegenwart und Perl 6 ist
die Zukunft.

Die Zahl nach perl (z.B. die 5 bei Perl 5) ist sowohl die Hauptversionsnummer
des Perl interpreters als auch die Version der Sprache. Jede Hauptversion
hat signifikante Unterschiede durch die frühere Versionen nicht unterstützt
werden können.

Die aktuelle Hauptversion von Perl ist Perl 5 und wurde 1994 veröffentlicht.
Es kann Skripte von der früheren Version - Perl 4 (März 1991) - laufen lassen,
aber sie hat starke Unterschiede. Sie hat das Konzept der Referenzen, komplexe
Datenstrukturen und Module eingeführt. Für den Perl 5 Interpreter wurden die
früheren Perl-Sourcen komplett neu geschrieben.

Perl 6 ist die nächste Hauptversion von Perl, aber das ist noch in Entwicklung,
sowohl bei der Syntax als auch im Design. Die Arbeit startete im Jahr 2002 und
läuft immer noch. Viele der interessantesten Features tauchen auch in der aktuellsten
Version von Perl 5 auf und einige Perl 5 Module ermöglichen es Dir, einiges der
Perl 6 Syntax in Deinen Programmen zu verwenden. Du kannst mehr über Perl 6 unter
http://dev.perl.org/perl6/ lernen.

Für eine Historie der Perl Revisionen, siehe L<perlhist>.

=head2 Was war Ponie?

(beigetragen von brian d foy)

Ponie steht für "Perl On the New Internal Engine" und wurd von Arthur
Bergmann von Fotango im Jahre 2003 begonnen. Und es lief später als
ein Projekt der Perl Foundation. Es wurde 2006 abgebrochen
( http://www.nntp.perl.org/group/perl.ponie.dev/487 ).

Anstatt die aktuellen Perl-Interna zu nutzen, zielte Ponie darauf ab,
neue Interna zu schaffen, die einen Weg für die Übersetzung von Perl 5
nach Perl 6 (oder irgendetwas anderes, das Parrot unterstützt) bieten.
Du wärst in der Lage gewesen, Perl 5 einfach mit Parrot, der Virtuellen
Maschine die Perl 6 Bytecode kompilieren und laufen lassen kann, zu benutzen.

=head2 Was ist Perl 6?

Auf der zweiten O'Reilly Open Source Software Convention hat Larry Wall
angekündigt, dass die Perl 6 Entwicklung ernsthaft anfangen würde. Perl 6
war ein oft benutzter Ausdruck für Chip Salzenbergs Projekt, Perl unter dem Namen
Topaz in C++ neu zu schreiben. Wie auch immer, Topaz bot wertvolle Einblicke in
die nächste Version von Perl und deren Implementierung. Aber das Projekt wurde
letztendlich abgebrochen.

Wenn du mehr über Perl6 lernen, oder am Kreuzzug, der Perl verbessern soll, 
teilnehmen willst, dann lies die Perl6-Entwicklerseiten auf http://dev.perl.org/perl6/ 
und mach mit.

Perl6 ist noch nicht zur Veröffentlichung angekündigt und Perl5 wird noch eine Weile nach 
seiner Veröffentlichung unterstützt werden. Warte mit dem, was du zu tun hast nicht auf Perl6.

"Wir nehmen es sehr ernst mit dem Neuerfinden von all dem, das neuerfunden werden muss." --Larry Wall 

=head2 Wie stabil Perl?

Production releases, which incorporate bug fixes and new functionality,
are widely tested before release.  Since the 5.000 release, we have
averaged only about one production release per year.

Larry and the Perl development team occasionally make changes to the
internal core of the language, but all possible efforts are made toward
backward compatibility.  While not quite all Perl 4 scripts run flawlessly
under Perl 5, an update to perl should nearly never invalidate a program
written for an earlier version of perl (barring accidental bug fixes
and the rare new keyword).

=head2 Ist Perl schwierig zu (er)lernen?

No, Perl is easy to start learning--and easy to keep learning.  It looks
like most programming languages you're likely to have experience
with, so if you've ever written a C program, an awk script, a shell
script, or even a BASIC program, you're already partway there.

Most tasks only require a small subset of the Perl language.  One of
the guiding mottos for Perl development is "there's more than one way
to do it" (TMTOWTDI, sometimes pronounced "tim toady").  Perl's
learning curve is therefore shallow (easy to learn) and long (there's
a whole lot you can do if you really want).

Finally, because Perl is frequently (but not always, and certainly not by
definition) an interpreted language, you can write your programs and test
them without an intermediate compilation step, allowing you to experiment
and test/debug quickly and easily.  This ease of experimentation flattens
the learning curve even more.

Things that make Perl easier to learn: Unix experience, almost any kind
of programming experience, an understanding of regular expressions, and
the ability to understand other people's code.  If there's something you
need to do, then it's probably already been done, and a working example is
usually available for free.  Don't forget Perl modules, either.
They're discussed in Part 3 of this FAQ, along with CPAN, which is
discussed in Part 2.

=head2 Wie ist Perl im Vergleich zu anderen Sprachen wie Java, Python, REXX, Scheme oder Tcl?

Favorably in some areas, unfavorably in others.  Precisely which areas
are good and bad is often a personal choice, so asking this question
on Usenet runs a strong risk of starting an unproductive Holy War.

Probably the best thing to do is try to write equivalent code to do a
set of tasks.  These languages have their own newsgroups in which you
can learn about (but hopefully not argue about) them.

Some comparison documents can be found at http://www.perl.com/doc/FMTEYEWTK/versus/
if you really can't stop yourself.

=head2 Kann ich [Aufgabe] in Perl erledigen?

Perl is flexible and extensible enough for you to use on virtually any
task, from one-line file-processing tasks to large, elaborate systems.
For many people, Perl serves as a great replacement for shell scripting.
For others, it serves as a convenient, high-level replacement for most of
what they'd program in low-level languages like C or C++.  It's ultimately
up to you (and possibly your management) which tasks you'll use Perl
for and which you won't.

If you have a library that provides an API, you can make any component
of it available as just another Perl function or variable using a Perl
extension written in C or C++ and dynamically linked into your main
perl interpreter.  You can also go the other direction, and write your
main program in C or C++, and then link in some Perl code on the fly,
to create a powerful application.  See L<perlembed>.

That said, there will always be small, focused, special-purpose
languages dedicated to a specific problem domain that are simply more
convenient for certain kinds of problems.  Perl tries to be all things
to all people, but nothing special to anyone.  Examples of specialized
languages that come to mind include prolog and matlab.

=head2 Wann sollte ich nicht in Perl programmieren?

When your manager forbids it--but do consider replacing them :-).

Actually, one good reason is when you already have an existing
application written in another language that's all done (and done
well), or you have an application language specifically designed for a
certain task (e.g. prolog, make).

For various reasons, Perl is probably not well-suited for real-time
embedded systems, low-level operating systems development work like
device drivers or context-switching code, complex multi-threaded
shared-memory applications, or extremely large applications.  You'll
notice that perl is not itself written in Perl.

Perl remains fundamentally a dynamically typed language, not
a statically typed one.  You certainly won't be chastised if you don't
trust nuclear-plant or brain-surgery monitoring code to it.  And Larry
will sleep easier, too--Wall Street programs not withstanding. :-)

=head2 Was ist der Unterschied zwischen "perl" und "Perl"?

Ein Bit. Oha, es ging gar nicht um ASCII? :-) Larry verwendet nun "Perl" 
um damit die Sprache selbst zu bezeichen und "perl" für ihre Implementation, 
also den aktuellen Interpreter. Daher kommt Tom's Ausspruch "Nur perl kann 
Perl parsen." 

Before the first edition of I<Programming perl>, people commonly
referred to the language as "perl", and its name appeared that way in
the title because it referred to the interpreter. In the book, Randal
Schwartz capitalised the language's name to make it stand out better
when typeset. This convention was adopted by the community, and the
second edition became I<Programming Perl>, using the capitalized
version of the name to refer to the language.

Du kannst es genau so halten oder anders. Zum Beispiel sieht 
sowohl "awk und perl" als auch "Python and Perl" ganz ok aus, während "awk 
und Perl" und "Python und perl" nicht so gut aussieht. Schreibe jedoch niemals 
"PERL", denn Perl ist kein Akronym, egal was apokryphe Folklore und 
spätere Erklärungen dazu sagen.

=head2 Ist es ein Perl-Programm oder ein Perl-Skript?

Larry doesn't really care.  He says (half in jest) that "a script is
what you give the actors.  A program is what you give the audience."

Originally, a script was a canned sequence of normally interactive
commands--that is, a chat script.  Something like a UUCP or PPP chat
script or an expect script fits the bill nicely, as do configuration
scripts run by a program at its start up, such F<.cshrc> or F<.ircrc>,
for example.  Chat scripts were just drivers for existing programs,
not stand-alone programs in their own right.

A computer scientist will correctly explain that all programs are
interpreted and that the only question is at what level.  But if you
ask this question of someone who isn't a computer scientist, they might
tell you that a I<program> has been compiled to physical machine code
once and can then be run multiple times, whereas a I<script> must be
translated by a program each time it's used.

Now that "script" and "scripting" are terms that have been seized by
unscrupulous or unknowing marketeers for their own nefarious purposes,
they have begun to take on strange and often pejorative meanings,
like "non serious" or "not real programming".  Consequently, some Perl
programmers prefer to avoid them altogether.

=head2 Was ist ein JAPH?

(beigetragen von brian d foy)

JAPH steht für "Just another Perl hacker,", das Randal Schwartz in den späten
1980er zum Unterschreiben seiner Emails und Usenet-Nachrichten benutzt hat.
Vorher hat er diesen Ausdruck mit vielen Dingen verwendet ("Just another x hacker,").
Zur Trennung seiner JAPH, begann er diese als Perl-Programm zu schreiben:

	print "Just another Perl hacker,";

Andere Leute haben das aufgenommen und begannen clevere oder verwirrende
Programme zu schreiben, die das gleiche ausgegeben haben. Die Dinge gerieten
schnell außer Kontrolle, während sie ihren Schöpfern und Lesern
noch Stunden der Vergnügung beschehrten.

Auf CPAN gibt es verschiedene JAPH Programme unter http://www.cpan.org/misc/japh .

=head2 Wo kann ich eine Liste von Larry Walls Witzeleien finden?

(beigetragen von brian d foy)

Google "larry wall quotes"! Du könntest sogar den "Auf gut Glück!"-Button versuchen.
:)

Wikiquote hat die Witze von Larry Wall mit deren Quellen, einschließlich
seiner Usenet-Beiträge und Quellcode-Kommentare.

Wenn Du eine einfache Textdatei haben möchtest, versuche es mit
http://www.cpan.org/misc/lwall-quotes.txt.gz .

=head2 Wie kann ich andere überreden, Perl zu benutzen?

(contributed by brian d foy)

Appeal to their self interest! If Perl is new (and thus scary) to them,
find something that Perl can do to solve one of their problems. That
might mean that Perl either saves them something (time, headaches, money)
or gives them something (flexibility, power, testability).

In general, the benefit of a language is closely related to the skill of
the people using that language. If you or your team can be more faster,
better, and stronger through Perl, you'll deliver more value. Remember,
people often respond better to what they get out of it. If you run
into resistance, figure out what those people get out of the other
choice and how Perl might satisfy that requirement.

You don't have to worry about finding or paying for Perl; it's freely
available and several popular operating systems come with Perl. Community
support in places such as Perlmonks ( http://www.perlmonks.com )
and the various Perl mailing lists ( http://lists.perl.org ) means that
you can usually get quick answers to your problems.

Finally, keep in mind that Perl might not be the right tool for every
job. You're a much better advocate if your claims are reasonable and
grounded in reality. Dogmatically advocating anything tends to make
people discount your message. Be honest about possible disadvantages
to your choice of Perl since any choice has trade-offs.

Vielleicht findest Du diese Links hilfreich:

=over 4

=item * http://perltraining.com.au/whyperl.html

=item * http://www.perl.org/advocacy/whyperl.html

=back

=head1 REVISION

Revision: $Revision$

Datum: $Date$

Für Details über Versionskontrolle und Verfügbarkeit siehe L<perlfaq>.

=head1 AUTOR UND COPYRIGHT

Copyright (c) 1997-2009 Tom Christiansen, Nathan Torkington und andere
Autoren wie genannt. Alle Rechte vorbehalten.

Diese Dokument ist frei; Du kannst es unter den gleichen Bedingungen wie
Perl selbst weiterverteilen und/oder verändern.

Unabhängig von der Verteilung, sind alle Code-Beispiele Gemeingut. Dir wird 
erlaubt und du wirst ermutigt, sie und beliebige davon abgeleitete in deinen 
Programmen zum Spaß oder für Profit zu verwenden. 
Ein einfacher Kommentar im Code, der die FAQ würdigt, wäre nett, ist aber 
nicht erforderlich. 
